### ISSUE TITLE
VSCode is duplicated

### ISSUE THREAD

**Issue by jasonLaster** [Nagasaki45/krihelinator#99]
It shows up twice on the list:

![screen shot 2017-01-21 at 11 06 56 pm](https://cloud.githubusercontent.com/assets/254562/22179907/5cb6b716-e02e-11e6-8ee0-916d52842bff.png)

**Comment by 7c6f434c** [comment]
And I think the list has two different mirrors of LLVM.

**Comment by Nagasaki45** [comment]
@jasonLaster, this is a bug. I will handle it soon. Meanwhile, I deleted one of the instances manually.

@7c6f434c, you are right, but there is nothing I can do against it. With the simple metric I use they both look like legitimate projects on GitHub that worth tracking. If you have an idea of how to detect the "unofficial" automatically do tell.

**Comment by 7c6f434c** [comment]
It is hard to define «unofficial», but I am not complaining about Chromium here. The only formal definition that would make some sense is being developed on GitHub, i.e. at least one PR in the last year or something like that. That would limit the scope, of course, so that's just a judgement call, not a bug fix.

As for the bug with clones: I am not sure about feasibility with the current API, but I would fetch the `master` commits from 1th December 2016 (the latest 1st that is more than a month ago) and look for intersections. If two LLVMs have had the same `master` branch a month ago, pick the higher-ranking one. Maybe add a small note «there are other instances of the same project» if you feel like that.

**Comment by Nagasaki45** [comment]
These are good propositions! I opened a separate ticket for handling them (#102). The vscode issue is really a simple bug that I need to fix. Let's keep the current ticket for that issue and move the discussion to the new thread.
